# Generated by Django 3.2.22 on 2023-10-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
